#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for test stand
#
# IDENTIFICATION
#    src/backend/stand/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/stand
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	stand_delay_setter.o \
	stand_handlers.o \

include $(top_srcdir)/src/backend/common.mk